version: '3.0'
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    depends_on:
      - db
      - pgadmin
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/srv/backend
    ports:
     - "8000:8000"
  
  mailhog:
    image: mailhog/mailhog:latest
    container_name: frankiecms-mailhog
    ports:
      - "8003:1025"
      - "8100:8025"

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgres/data/pgdata
    env_file:
      - ./backend/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
     - "15432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "16543:80"
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
    